services:
  audio:
    labels:
      dev.okteto.com/public: "true"
    build:
      dockerfile: Dockerfile01
    deploy:
      mode: replicated
      replicas: 1
    oom_kill_disable:
    mem_swappiness: 100
    restart: on-failure    
    ports:
      - 8080:8080
