services:
  mon:
    labels:
      dev.okteto.com/public: "true"
    build:
      dockerfile: Dockerfile01
    ports:
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 10
    oom_kill_disable:
    mem_swappiness: 100
    restart: on-failure  
